upgrade log4j
johnrengelman/shadow pull request #740
Opened 2021-12-20 11:48 UTC by daroga0002

Upgrade log4j due [CVE-2021-45105](https://github.com/advisories/GHSA-p6xc-xr62-6r2g)

2021-12-20 11:49 UTC, daroga0002 commented
@johnrengelman this is next log4j CVE upgrade

2021-12-21 20:27 UTC, jschulte approved these changes

2021-12-23 13:21 UTC, stewartyoung approved these changes

2021-12-23 17:50 UTC, Goooler approved these changes

2021-12-27 14:18 UTC, daroga0002 commented
@johnrengelman  can you take a look?

2021-12-28 22:54 UTC, EncryptSL requested changes
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-44832

Sorry mate but you must change to 2.17.1

2021-12-29 01:06 UTC, johnrengelman commented
Closed in 0bc5443b61de16808fa95edb168150fa3cc462b6

2021-12-29 01:06 UTC, closed without merging